### ISSUE TITLE
Multi-line indent and wrapping error

### ISSUE THREAD

**Issue by shyamdadimuni** [jonmiles/bootstrap-treeview#149]
When child has a multi line, indention only apply for first line, and  some lines not wrap properly. See attached screenshot. 

Thanks

![indent_error](https://cloud.githubusercontent.com/assets/5640095/11659280/6f6abdf8-9d95-11e5-965d-700aa1ad1b14.PNG)

**Comment by shyamdadimuni** [comment]
I fixed this by replacing indent Span with simple CSS.

Replaced following (bootstrap-treeview.js line 523 to 526.)

                       // Add indent/spacer to mimic tree structure
			for (var i = 0; i < (level - 1); i++) {
				treeItem.append(_this.template.indent);
			}

with this simple calculation.

                       // Add indent/spacer to mimic tree structure
			var spaceCal = 5;
			for (var i = 0; i < (level - 1); i++) {
				spaceCal += 12;
			}
		        treeItem.css("padding-left", spaceCal + 'px');

Hopefully this helps to solve this problem in your plugin.

Happy coding...!!!
Shyam

**Comment by ypnos-web** [comment]
Your solution is pretty, good, although it does not solve the problem with badges on overfloat.
How about you make a pull request?
For that however I would use an initial padding of **15** and additional padding of **20**, resembling the current behavior.

**Comment by shyamdadimuni** [comment]
I solved the over-float by adding padding-right for main <ul>.

**Comment by jvanakker** [comment]
shyamdadimuni's solution from dec-8 doesn't solve the text wrapping problem for me... It just shifts the whole thing to the right, instead of the next (wrapepd) line.

Any ideas?

**Comment by occasl** [comment]
I see the same thing. We want the next wrapped line to be lined up with the line above.  In your example "Hints" should be directly under "2-D".
